### ISSUE TITLE
Errors in reporting bugs

### ISSUE THREAD

**Issue by pcav** [lutraconsulting/qgis-report-plugin#31]
Steps to reproduce
Just adding the token, the description, and clicking SUBMIT (BTW: better 'Submit' IMHO) triggers the error.

```
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/report/main_widget.py", line 246, in _submit_issue
    link, number = self.selected_provider.create_issue(title, labels, u'{}\n{}'.format(desc, additional_info))
  File "/home/paolo/.qgis2/python/plugins/report/providers/github.py", line 85, in create_issue
    return resp['html_url'], resp['number']
KeyError: 'html_url'

```

**Comment by PeterPetrik** [comment]
I cannot reproduce it with version 0.2.1. Can you please provide to which github repository/plugin the issue was reported? It should not be possible to submit issue without title, are you sure you have just added token and description? Thanks.

**Comment by pcav** [comment]
https://github.com/mariofraga/sipamsar/issues

Yes, the title is added automatically (in this case: Uncaught AttributeError: 'NoneType' object has no attribute 'dataProvider'
 )

**Comment by PeterPetrik** [comment]
@pcav 
hmm, could you please add 
"print resp" 
on line line 84 (before return statement) in file
/home/paolo/.qgis2/python/plugins/report/providers/github.py
, restart QGIS, open python console, reproduce the bug and sent me the resp JSON? Thanks.

**Comment by pcav** [comment]
Sorry, no time for these tests right now. I have a long queue of plugins to manage, and that's voluntary work.
