### ISSUE TITLE
Provide help on which kind of permission the token should have

### ISSUE THREAD

**Issue by pcav** [lutraconsulting/qgis-report-plugin#34]
GitHub may present an intimidating series of options for generating the token. A suggestion on the minimum set of permissions necessary would be good.

**Comment by PeterPetrik** [comment]
In version 0.2.1, there is "Help" button in the configuration dialog, with screenshot of minimum set of permissions necessary. I am not sure where else the suggestion should be put? In the README file?
Thanks for clarification

**Comment by pcav** [comment]
You're right, I overlooked the help, sorry for the noise.
